image: python:3.9.9

before_script:
  - python --version

  # redirect of the Huawei mirror
  - echo -e "[global]\nindex-url = http://mirrors.tools.huawei.com/pypi/simple\ntrusted-host = mirrors.tools.huawei.com\ntimeout = 120" > ~/.pip/pip.conf

  # install Bandpy package
  - pip install -r requirements.txt
  - pip install -e .

  # install usefull CI tools
  - pip install pytest pytest-cov coverage flake8

stages:
  - test
  - example-basic
  - example-illustration
  - example-benchmark

unit-test:
  stage: test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  script:
    - flake8 --count bandpy
    - pytest -vl --cov=bandpy --cov-append
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

example_basic:
  stage: example-basic
  script:
    - cd examples/0_basics/
    - python 0_ellipsoid_overlapping.py

example_illustration:
  stage: example-illustration
  script:
    - cd examples/1_illustrations/
    - python 0_demo_lin_ucb.py
    - python 1_demo_quad_ucb.py

example_benchmark:
  stage: example-benchmark
  script:
    - cd examples/2_benchmark/
    - python 0_demo_mab_benchmark.py
    - python 1_demo_lb_benchmark_no_clustering.py
    - python 2_demo_lb_benchmark_clustering.py
