image: python:latest

before_script:
  - python --version

  # redirect of the Huawei mirror
  - echo -e "[global]\nindex-url = http://mirrors.tools.huawei.com/pypi/simple\ntrusted-host = mirrors.tools.huawei.com\ntimeout = 120" > ~/.pip/pip.conf

  # install Bandpy package
  - pip install -r requirements.txt
  - pip install -e .

  # install usefull CI tools
  - pip install pytest pytest-cov coverage flake8

stages:
  - test
  - example

unit-test:
  stage: test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  script:
    - flake8 --count bandpy
    - pytest -vl --cov=bandpy --cov-append
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
