language: python
python: "3.6"

install:
    # install Bandpy package
    - pip install -r requirements.txt
    - pip install -e .

    # install usefull CI tools
    - pip install pytest pytest-cov coverage flake8

script:
    - set -e
    - flake8 --ignore=E501 --count bandpy
    - pytest -vl --cov=bandpy --cov-append

after_success:
    - codecov

notifications:
    email: false
